/**
 * FHEVM Integration Layer
 * Handles encryption/decryption using Relayer SDK or Mock Utils
 */

import type { FhevmInstance, FhevmConfig } from "./fhevmTypes";
import { FHEVM_CONSTANTS } from "./constants";
import { fhevmStorage } from "@/utils/storage";

let cachedInstance: FhevmInstance | null = null;
let currentConfig: FhevmConfig | null = null;

/**
 * Initialize FHEVM instance based on network type
 */
export async function initFhevm(config: FhevmConfig): Promise<FhevmInstance> {
  // Return cached instance if config matches
  if (
    cachedInstance &&
    currentConfig &&
    currentConfig.chainId === config.chainId &&
    currentConfig.account === config.account &&
    currentConfig.isMock === config.isMock
  ) {
    return cachedInstance;
  }

  if (config.isMock) {
    // Use mock utils for localhost
    const { createFhevmMockInstance } = await import("./mock/fhevmMock");
    const rpcUrl = config.rpcUrl || "http://localhost:8545";
    cachedInstance = await createFhevmMockInstance(config.chainId, rpcUrl);
  } else {
    // Use Relayer SDK for production
    const { createFhevmRelayerInstance } = await import("./RelayerSDKLoader");
    cachedInstance = await createFhevmRelayerInstance(config.chainId, config.account);
  }

  currentConfig = config;
  return cachedInstance;
}

/**
 * Get current FHEVM instance (throws if not initialized)
 */
export function getFhevmInstance(): FhevmInstance {
  if (!cachedInstance) {
    throw new Error("FHEVM not initialized. Call initFhevm() first.");
  }
  return cachedInstance;
}

/**
 * Reset FHEVM instance (useful when switching accounts/networks)
 */
export function resetFhevm(): void {
  cachedInstance = null;
  currentConfig = null;
}

/**
 * Check if FHEVM is initialized
 */
export function isFhevmInitialized(): boolean {
  return cachedInstance !== null;
}

// Note: encrypt32/encrypt64/decrypt32/decrypt64 functions removed
// Use instance.createEncryptedInput() + encrypt() instead for encryption
// Use userDecrypt() from useDecryption hook for decryption

/**
 * Get public key for current network
 */
export function getPublicKey(): string {
  const instance = getFhevmInstance();
  return instance.getPublicKey();
}

// Note: createInputProof removed - input proofs are generated by encrypt() method

